apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    createdAt: "2026-02-23T22:47:52Z"
    operators.operatorframework.io/builder: operator-sdk-v1.42.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: stellar-operator.v0.1.0
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Stellar-K8s Operator manages Stellar nodes within Kubernetes.
  displayName: Stellar K8s Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - stellar
  - blockchain
  - node
  links:
  - name: Stellar-K8s
    url: https://github.com/0xOlivanode/Stellar-K8s
  maintainers:
  - email: info@0xolivanode.io
    name: 0xOlivanode
  maturity: alpha
  minKubeVersion: 1.20.0
  provider:
    name: 0xOlivanode
  version: 0.1.0
