{{- if and .Values.secrets.create .Values.secrets.useExternalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "stellar-operator.fullname" . }}-secrets
  labels:
    {{- include "stellar-operator.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.secrets.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.secrets.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "stellar-operator.fullname" . }}-secrets
    creationPolicy: Owner
  data:
  {{- range $name, $config := .Values.secrets.items }}
  - secretKey: {{ $config.key | quote }}
    remoteRef:
      key: {{ $config.value | quote }}
  {{- end }}
{{- end }}
