{{- if and .Values.secrets.create (not .Values.secrets.useExternalSecrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stellar-operator.fullname" . }}-secrets
  labels:
    {{- include "stellar-operator.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.secrets.items }}
data:
  {{- range $name, $config := .Values.secrets.items }}
  {{ $config.key }}: {{ $config.value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
